name: Model CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]

jobs:
  validate:
    runs-on: ubuntu-latest
    # CRITICAL: All 3 secrets must be here so train.py can log into DagsHub!
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mlflow dvc

      - name: Pull Data
        run: echo "Simulating DVC pull..."

      - name: Train Model and Log to MLflow
        run: python train.py

      - name: Export Run ID Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-info-artifact
          path: model_info.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    # CRITICAL: All 3 secrets must be here so check_threshold.py can read from DagsHub!
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mlflow

      - name: Retrieve Run ID Artifact
        uses: actions/download-artifact@v4
        with:
          name: model-info-artifact

      - name: Validate Accuracy Threshold
        run: python check_threshold.py

      - name: Mock Docker Containerization
        run: |
          RUN_ID=$(cat model_info.txt)
          echo "Building Docker image for Run ID: $RUN_ID"
          docker build --build-arg RUN_ID=$RUN_ID -t production_model:$RUN_ID . --fail