name: Model CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]

jobs:
  validate:
    runs-on: ubuntu-latest
    # Inject the MLflow tracking URI securely
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mlflow dvc

      - name: Pull Data
        run: |
          # Initialize/Run DVC to pull the dataset
          # dvc pull
          echo "Simulating DVC pull..."

      - name: Train Model and Log to MLflow
        run: |
          # NOTE: To get your "Failed" screenshot, change this to: python train.py --fail
          python train.py

      - name: Export Run ID Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-info-artifact
          path: model_info.txt

  deploy:
    needs: validate # Forces this job to wait for validation
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mlflow

      - name: Retrieve Run ID Artifact
        uses: actions/download-artifact@v4
        with:
          name: model-info-artifact
          # By default, v4 downloads directly into the current working directory

      - name: Validate Accuracy Threshold
        run: python check_threshold.py

      - name: Mock Docker Containerization
        # This only runs if the previous step exits with 0 (success)
        run: |
          RUN_ID=$(cat model_info.txt)
          echo "Building Docker image for Run ID: $RUN_ID"
          docker build --build-arg RUN_ID=$RUN_ID -t production_model:$RUN_ID .
